### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by JulyStar-Lv** [BetterAndroid/compose-multiplatform-template#1]
大佬，编译错误，查的方法好像都没用
`Build was configured to prefer settings repositories over project repositories but repository 'ivy' was added by build file 'shared/build.gradle.kts'`
官方提供模版是正常的 [compose-multiplatform-ios-android-template](https://github.com/JetBrains/compose-multiplatform-ios-android-template)

**Comment by fankes** [comment]
通过插件管理的存储库不可以使用 repositories 进行管理，请检查你是否在 shared 构建脚本中添加了 ivy 存储库并重试，目前插件暂不支持 ivy 格式的存储库

由于你没有提供更多关于配置自己项目的有效信息，无法定位问题，该问题将被关闭，如有其他问题请继续留言

**Comment by fankes** [comment]
我找人测试了一下，看起来好像有人有同样的问题，等我再看看是什么情况

**Comment by fankes** [comment]
初步推断 kmm 更新了奇怪的东西，用 repositories 设置了自定义存储库，但是存储库已经被 [SweetDependency](https://github.com/HighCapable/SweetDependency) 接管了，它的规则是在 settings.gradle 设置了自定义存储库，那么每个构建脚本里就不允许使用 repositories 配置块，应该需要等上游调整或者修复，或者删除 iOS 相关的配置

**Comment by fankes** [comment]
后期更新插件解决，会在这里同步进度

**Comment by fankes** [comment]
该问题已被修复，你可以重新尝试创建项目或者按照当前模版的 settings.gradle.kts 进行配置。
